In [1]:
import torch

### Initializing Tensor

In [2]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                         device='cuda')
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [5]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                         device='cpu')
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                         device=device)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [7]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                         device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [8]:
my_tensor.dtype

torch.float32

In [11]:
my_tensor.device

device(type='cuda', index=0)

In [12]:
my_tensor.shape

torch.Size([2, 3])

In [13]:
my_tensor.requires_grad

True

#### Other common initialization methods

In [26]:
x = torch.empty(size = (3, 3))
print(x)
x = torch.zeros((3, 3))
print(x)
x = torch.rand((3, 3))
print(x)
x = torch.ones((3, 3))
print(x)
x = torch.eye(3, 3) # I, eye
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)
x = torch.empty(size=(1, 5)).uniform_(0, 1)
print(x)
x = torch.diag(torch.ones(3), -1) # diag, ie. diagonal(line)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0570, 0.4655, 0.6775],
        [0.9057, 0.4578, 0.1428],
        [0.7218, 0.4763, 0.2224]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[ 0.1723,  0.8684,  1.3210, -0.5318,  0.1820]])
tensor([[0.7965, 0.5497, 0.2181, 0.8402, 0.0058]])
tensor([[0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


#### How to initialize and convert tensors to other types (int, float, double)

In [39]:
tensor = torch.arange(4)
print(tensor)
print(tensor.bool()) # boolean
print(tensor.short()) # torch.long() 将tensor投射为short类型, int16
print(tensor.long()) # torch.long() 将tensor投射为long类型, int64 (Important)
print(tensor.half()) # torch.half()将tensor投射为半精度浮点类型 float16
print(tensor.float()) # float32 (Important)
print(tensor.double()) # float64


tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


#### Array to Tensor conversion and vice-versa

In [40]:
import numpy as np

In [43]:
np_array = np.zeros((5, 5))
print(np_array)
tensor = torch.from_numpy(np_array)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
