In [1]:
import torch

### Tensor Indexing

In [7]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape) # x[0, :]

print(x[:, 0].shape)

print(x[2, 0:10]) # 0;10 --> [0, 1, 2, ..., 9]

x[0, 0] = 100

torch.Size([25])
torch.Size([10])
tensor([0.8077, 0.3211, 0.5987, 0.4828, 0.8832, 0.3124, 0.4831, 0.4473, 0.5664,
        0.9764])


In [19]:
# Fancy indexing
x = torch.arange(111)
indices = [2, 4, 8]
print(x[indices])

x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols].shape)

tensor([2, 4, 8])
torch.Size([2])


In [22]:
# More advanced indexing
x = torch.arange(11)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2) == 0])

tensor([ 0,  1,  9, 10])
tensor([ 0,  2,  4,  6,  8, 10])


In [24]:
# Useful operations
print(torch.where(x > 5, x, x*2)) # x --> if x > 5 x=x else x = x*2
print(torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique())
print(x.ndimension()) # 5x5x5 --> 3
print(x.numel()) # how many number

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9, 10])
tensor([0, 1, 2, 3, 4])
1
11
