In [1]:
import torch

### Tensor Reshaping

In [7]:
x = torch.arange(9)

x_3x3 = x.view(3, 3)
print(x_3x3)

print(x_3x3.shape)

y = x_3x3.t()
print(y)
# print(y.view(9)) # y is not contiguous
print(y.contiguous().view(9))

# 当变量空间连续时，reshape()与view()等同
# 当变量空间不连续时，reshape()与x.contiguous().view()等同
x_3x3 = x.reshape(3, 3)
print(x_3x3)
y = x_3x3.t()
print(y)
print(y.reshape(9))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [8]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [9]:
z = x1.view(-1)
print(z.shape)

torch.Size([10])


In [10]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [11]:
z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 5, 2])


In [13]:
x = torch.arange(10) # [10]
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [15]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1x1x10
print(x.shape)

z = x.squeeze(1)
print(z.shape)

torch.Size([1, 1, 10])
torch.Size([1, 10])
